# Generated by Django 4.1 on 2022-08-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
