# Generated by Django 4.1 on 2022-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetShopApp', '0003_alter_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
