# Generated by Django 4.1 on 2022-08-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetShopApp', '0005_demensionalgridtypes_productsign_productssize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productssize',
            name='demensional_grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternetShopApp.demensionalgridtypes'),
        ),
        migrations.AddField(
            model_name='productsstorage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternetShopApp.products'),
        ),
        migrations.AddField(
            model_name='productsstorage',
            name='product_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternetShopApp.productsign'),
        ),
        migrations.AddField(
            model_name='productsstorage',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternetShopApp.productssize'),
        ),
    ]
