# Generated by Django 4.1 on 2022-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetShopApp', '0007_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
