# Generated by Django 4.1 on 2022-08-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetShopApp', '0008_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
    ]
